-- MySQL Script generated by MySQL Workbench
-- Fri Dec 21 22:09:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `idEquipment` INT NOT NULL,
  `mainWeapon` INT NOT NULL,
  `secWeapon` INT NOT NULL,
  `arm` INT NOT NULL,
  `acc` INT NULL,
  `potHP` INT NULL,
  `potMP` INT NULL,
  PRIMARY KEY (`idEquipment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Character` (
  `idCharacter` INT NOT NULL,
  `hp` INT NULL,
  `mp` INT NULL,
  `nome` VARCHAR(45) NULL,
  `classe` VARCHAR(45) NULL,
  `raca` VARCHAR(45) NULL,
  `fatk` INT NULL,
  `matk` INT NULL,
  `str` INT NULL,
  `inte` INT NULL,
  `agi` INT NULL,
  `vit` INT NULL,
  `car` INT NULL,
  `dex` INT NULL,
  `sab` INT NULL,
  `level` INT NOT NULL,
  `def` INT NULL,
  `crit` INT NULL,
  `modCar` INT NULL,
  `modSab` INT NULL,
  `modDex` INT NULL,
  `Equipment_idEquipment` INT NOT NULL,
  PRIMARY KEY (`idCharacter`, `Equipment_idEquipment`),
  INDEX `fk_Character_Equipment_idx` (`Equipment_idEquipment` ASC),
  CONSTRAINT `fk_Character_Equipment`
    FOREIGN KEY (`Equipment_idEquipment`)
    REFERENCES `mydb`.`Equipment` (`idEquipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
