/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dgnrpg.view;

import dgnrpg.DAO;
import dgnrpg.DeBuffs;
import dgnrpg.controller.BerrrtaController;
import dgnrpg.controller.LevelUpController;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Bruno Balestra
 */
public class TelaRosa extends javax.swing.JFrame {

     DAO aux = DAO.getInstance();
     BerrrtaController ber= BerrrtaController.getInstance();
     public int x =1;
     public int damage=0;
     public int heal=0;
     public ArrayList<String> lista = new ArrayList();
     public int turnos;
      
    
     
    public TelaRosa() {
        initComponents();

        strTxt.setText(Integer.toString(aux.getPersonagem(5).getStr()));
        intTxt.setText(Integer.toString(aux.getPersonagem(5).getInte()));
        agiTxt.setText(Integer.toString(aux.getPersonagem(5).getAgi()));
        vitTxt.setText(Integer.toString(aux.getPersonagem(5).getVit()));
        carTxt.setText(Integer.toString(aux.getPersonagem(5).getCar()));
        dexTxt.setText(Integer.toString(aux.getPersonagem(5).getDex()));
        sabTxt.setText(Integer.toString(aux.getPersonagem(5).getSab()));
        defTxt.setText(Integer.toString(aux.getPersonagem(5).getDef()));
        fatkTxt.setText(Integer.toString(aux.getPersonagem(5).getFatk()));
        matkTxt.setText(Integer.toString(aux.getPersonagem(5).getMatk()));
        critTxt.setText(Integer.toString(aux.getPersonagem(5).getCrit())+"%");
        mainWeaTxt.setText(Integer.toString(aux.getPersonagem(5).getMainWeapon()));
        secWeaTxt.setText(Integer.toString(aux.getPersonagem(5).getSecWeapon()));
        modCarTxt.setText("+"+Integer.toString(aux.getPersonagem(5).getModCar()));
        modSabTxt.setText("+"+Integer.toString(aux.getPersonagem(5).getModSab()));
        modDexTxt.setText("+"+Integer.toString(aux.getPersonagem(5).getModDex()));
        
        new Thread(){
            public void run(){
                try{               
                        System.out.println(aux.getPersonagem(5).getHP());
                        hpBar.setMaximum(aux.getPersonagem(5).getHP());
                        hpBar.setValue(aux.getPersonagem(5).getHP());   
                        hpBar.setString(Integer.toString(aux.rosa.getHpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getHP()));
                        
                        mpBar.setMaximum(aux.getPersonagem(5).getMP());
                        mpBar.setValue(aux.getPersonagem(5).getMP());     
                        mpBar.setString(Integer.toString(aux.rosa.getMpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getMP()));
                    sleep(10);        
                }
                catch(InterruptedException ex){
                    
                }
            }    
    }.start();
 }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hpBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        mpBar = new javax.swing.JProgressBar();
        damageBtn = new javax.swing.JButton();
        strTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        agiTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vitTxt = new javax.swing.JTextField();
        healBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        carTxt = new javax.swing.JTextField();
        dexTxt = new javax.swing.JTextField();
        sabTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnSkill = new javax.swing.JButton();
        cureBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fatkTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        matkTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        critTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        defTxt = new javax.swing.JTextField();
        modCarTxt = new javax.swing.JTextField();
        modDexTxt = new javax.swing.JTextField();
        modSabTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDebuffs = new javax.swing.JList<>();
        comboBdf = new javax.swing.JComboBox<>();
        comboDados = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        lvlUpBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        mainWeaTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        secWeaTxt = new javax.swing.JTextField();
        lvlUpBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Rosa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));

        jLabel1.setFont(new java.awt.Font("Orator Std", 0, 20)); // NOI18N
        jLabel1.setText("hp:");

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        jLabel2.setText("Rosa");

        hpBar.setForeground(java.awt.Color.red);
        hpBar.setStringPainted(true);

        jLabel3.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel3.setText("MP:");

        mpBar.setForeground(java.awt.Color.blue);
        mpBar.setFocusable(false);
        mpBar.setStringPainted(true);

        damageBtn.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        damageBtn.setText("Damage");
        damageBtn.setToolTipText("");
        damageBtn.setFocusable(false);
        damageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damageBtnActionPerformed(evt);
            }
        });

        strTxt.setEditable(false);
        strTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        strTxt.setText("jTextField1");
        strTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel4.setText("for:");

        jLabel5.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel5.setText("Int:");

        intTxt.setEditable(false);
        intTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intTxt.setText("jTextField1");
        intTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel6.setText("agi:");

        agiTxt.setEditable(false);
        agiTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agiTxt.setText("jTextField1");
        agiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agiTxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel7.setText("Vit:");

        vitTxt.setEditable(false);
        vitTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vitTxt.setText("jTextField1");
        vitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitTxtActionPerformed(evt);
            }
        });

        healBtn.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        healBtn.setText("Heal");
        healBtn.setFocusable(false);
        healBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel8.setText("Car:");

        jLabel9.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel9.setText("Dex:");

        jLabel10.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel10.setText("Sab:");

        carTxt.setEditable(false);
        carTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carTxt.setText("jTextField1");
        carTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTxtActionPerformed(evt);
            }
        });

        dexTxt.setEditable(false);
        dexTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dexTxt.setText("jTextField1");
        dexTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexTxtActionPerformed(evt);
            }
        });

        sabTxt.setEditable(false);
        sabTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sabTxt.setText("jTextField1");
        sabTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabTxtActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dgnrpg/view/Rosa.jpeg"))); // NOI18N
        jButton3.setFocusable(false);

        btnSkill.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        btnSkill.setText("Skill");
        btnSkill.setToolTipText("");
        btnSkill.setFocusable(false);
        btnSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkillActionPerformed(evt);
            }
        });

        cureBtn.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        cureBtn.setText("Cure");
        cureBtn.setToolTipText("");
        cureBtn.setFocusable(false);
        cureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cureBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel11.setText("fatk:");

        fatkTxt.setEditable(false);
        fatkTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fatkTxt.setText("jTextField1");
        fatkTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatkTxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel12.setText("matk:");

        matkTxt.setEditable(false);
        matkTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matkTxt.setText("jTextField1");
        matkTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkTxtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel13.setText("crit:");

        critTxt.setEditable(false);
        critTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        critTxt.setText("jTextField1");
        critTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                critTxtActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel14.setText("Def:");

        defTxt.setEditable(false);
        defTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        defTxt.setText("jTextField1");
        defTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defTxtActionPerformed(evt);
            }
        });

        modCarTxt.setEditable(false);
        modCarTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modCarTxt.setText("jTextField1");
        modCarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCarTxtActionPerformed(evt);
            }
        });

        modDexTxt.setEditable(false);
        modDexTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modDexTxt.setText("jTextField1");
        modDexTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDexTxtActionPerformed(evt);
            }
        });

        modSabTxt.setEditable(false);
        modSabTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modSabTxt.setText("jTextField1");
        modSabTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modSabTxtActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Orator Std", 0, 20)); // NOI18N
        jLabel15.setText("Buffs e Debuffs");

        listaDebuffs.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        listaDebuffs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDebuffsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaDebuffs);

        comboBdf.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        comboBdf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Damage - Debuff", "Lightning - Debuff", "Defense - Debuff", "Power - Buff", "Shield - Buff", " " }));
        comboBdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBdfActionPerformed(evt);
            }
        });

        comboDados.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        comboDados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "d4", "d6", "d8", "d10", "d12", "" }));

        jButton4.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        jButton4.setText("+");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lvlUpBtn.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        lvlUpBtn.setText("Level up");
        lvlUpBtn.setToolTipText("");
        lvlUpBtn.setFocusable(false);
        lvlUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvlUpBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel16.setText("1st Weapon:");

        mainWeaTxt.setEditable(false);
        mainWeaTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainWeaTxt.setText("jTextField1");
        mainWeaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainWeaTxtActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Orator Std", 0, 18)); // NOI18N
        jLabel17.setText("2nd Weapon:");

        secWeaTxt.setEditable(false);
        secWeaTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secWeaTxt.setText("jTextField1");
        secWeaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secWeaTxtActionPerformed(evt);
            }
        });

        lvlUpBtn1.setFont(new java.awt.Font("Orator Std", 0, 11)); // NOI18N
        lvlUpBtn1.setText("Equipamentos");
        lvlUpBtn1.setToolTipText("");
        lvlUpBtn1.setFocusable(false);
        lvlUpBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvlUpBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(mpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSkill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(damageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(intTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(vitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sabTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modSabTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(strTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fatkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(agiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(critTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dexTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modDexTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(carTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modCarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(secWeaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mainWeaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(healBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cureBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lvlUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(lvlUpBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboBdf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboDados, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(hpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(damageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(healBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lvlUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlUpBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(strTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fatkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(intTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(agiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(critTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(carTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modCarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(dexTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(modDexTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 2, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mainWeaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(secWeaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sabTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modSabTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(defTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(19, 19, 19))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sabTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabTxtActionPerformed

    private void dexTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexTxtActionPerformed

    private void carTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTxtActionPerformed

    private void healBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healBtnActionPerformed
        heal = Integer.parseInt(JOptionPane.showInputDialog(this, "Heal:",1));
        if(heal<=0){
            JOptionPane.showMessageDialog(this, "Cura Incorreta", "Erro!", JOptionPane.WARNING_MESSAGE);
        }else{
            if(aux.rosa.getHpAtual()<aux.rosa.getHP()){
                if(heal <= aux.getPersonagem(5).getHP()){
                    hpBar.setValue(aux.rosa.getHpAtual()+heal);
                    aux.rosa.setHpAtual(aux.rosa.getHpAtual()+heal);
                    System.out.println(aux.rosa.getHpAtual());
                    hpBar.setString(Integer.toString(aux.rosa.getHpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getHP()));
                    mpBar.setString(Integer.toString(aux.rosa.getMpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getMP()));
                }
                else{
                    JOptionPane.showMessageDialog(this, "HP cheio", "Aviso!", JOptionPane.WARNING_MESSAGE);
                    aux.rosa.setHpAtual(aux.rosa.getHP());
                    hpBar.setValue(aux.getPersonagem(5).getHP());
                    hpBar.setString(Integer.toString(aux.rosa.getHpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getHP()));

                }
            }
        }
    }//GEN-LAST:event_healBtnActionPerformed

    private void vitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitTxtActionPerformed

    private void agiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agiTxtActionPerformed

    private void intTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intTxtActionPerformed

    private void strTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strTxtActionPerformed

    private void damageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageBtnActionPerformed

        damage = Integer.parseInt(JOptionPane.showInputDialog(this, "Damage:",1));
        if(damage<=0){
            JOptionPane.showMessageDialog(this, "Dano Incorreto", "Erro!", JOptionPane.WARNING_MESSAGE);
        }else{
            if(aux.rosa.getHpAtual()>0){
                if(damage <=aux.rosa.getHpAtual()){

                    hpBar.setValue(aux.rosa.getHpAtual()-damage);
                    aux.rosa.setHpAtual(aux.rosa.getHpAtual()-damage);
                    System.out.println(aux.rosa.getHpAtual());
                    hpBar.setString(Integer.toString(aux.rosa.getHpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getHP()));
                    mpBar.setString(Integer.toString(aux.rosa.getMpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getMP()));
                    System.out.println(aux.rosa.getMpAtual()+ "MP MP MP");
                }
                else{
                    JOptionPane.showMessageDialog(this, "HP Chegou a zero", "Aviso!", JOptionPane.WARNING_MESSAGE);
                    aux.rosa.setHpAtual(0);
                    hpBar.setValue(aux.getPersonagem(5).getHpAtual());
                    hpBar.setString(Integer.toString(aux.rosa.getHpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getHP()));

                }
            }
        }
    }//GEN-LAST:event_damageBtnActionPerformed

    private void btnSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkillActionPerformed
        if(aux.rosa.getMpAtual()>0){
            
                    mpBar.setValue(aux.rosa.getMpAtual()-1);
                    aux.rosa.setMpAtual(aux.rosa.getMpAtual()-1);
                    mpBar.setString(Integer.toString(aux.rosa.getMpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getMP()));
 
            }
        else{
             JOptionPane.showMessageDialog(this, "Sem Mana!", "Aviso!", JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_btnSkillActionPerformed

    private void cureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cureBtnActionPerformed
      if(aux.rosa.getMpAtual()>=0&& aux.rosa.getMpAtual()<aux.rosa.getMP()){
            
                    mpBar.setValue(aux.rosa.getMpAtual()+1);
                    aux.rosa.setMpAtual(aux.rosa.getMpAtual()+1);
                    mpBar.setString(Integer.toString(aux.rosa.getMpAtual())+"/"+Integer.toString(aux.getPersonagem(5).getMP()));
 
            }
        else{
             JOptionPane.showMessageDialog(this, "Mana Cheia", "Aviso!", JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_cureBtnActionPerformed

    private void fatkTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatkTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatkTxtActionPerformed

    private void matkTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matkTxtActionPerformed

    private void critTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_critTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_critTxtActionPerformed

    private void defTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defTxtActionPerformed

    private void modCarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modCarTxtActionPerformed

    private void modDexTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDexTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modDexTxtActionPerformed

    private void modSabTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modSabTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modSabTxtActionPerformed

    private void comboBdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBdfActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      cadastraDbf();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lvlUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvlUpBtnActionPerformed
        LevelUpController l = LevelUpController.getInstance();
        l.criarJanela(aux.getPersonagem(5));
        this.dispose();
    }//GEN-LAST:event_lvlUpBtnActionPerformed

    private void listaDebuffsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDebuffsMouseClicked
        lista.clear();
        listaDebuffs.setModel(new DefaultListModel());
       
    }//GEN-LAST:event_listaDebuffsMouseClicked

    private void mainWeaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainWeaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainWeaTxtActionPerformed

    private void secWeaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secWeaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secWeaTxtActionPerformed

    private void lvlUpBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvlUpBtn1ActionPerformed
        LevelUpController l = LevelUpController.getInstance();
        l.criarJanelaEquip(aux.getPersonagem(5));
        this.dispose();
    }//GEN-LAST:event_lvlUpBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agiTxt;
    private javax.swing.JButton btnSkill;
    private javax.swing.JTextField carTxt;
    private javax.swing.JComboBox<String> comboBdf;
    private javax.swing.JComboBox<String> comboDados;
    private javax.swing.JTextField critTxt;
    private javax.swing.JButton cureBtn;
    private javax.swing.JButton damageBtn;
    private javax.swing.JTextField defTxt;
    private javax.swing.JTextField dexTxt;
    private javax.swing.JTextField fatkTxt;
    private javax.swing.JButton healBtn;
    public javax.swing.JProgressBar hpBar;
    private javax.swing.JTextField intTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaDebuffs;
    private javax.swing.JButton lvlUpBtn;
    private javax.swing.JButton lvlUpBtn1;
    private javax.swing.JTextField mainWeaTxt;
    private javax.swing.JTextField matkTxt;
    private javax.swing.JTextField modCarTxt;
    private javax.swing.JTextField modDexTxt;
    private javax.swing.JTextField modSabTxt;
    private javax.swing.JProgressBar mpBar;
    private javax.swing.JTextField sabTxt;
    private javax.swing.JTextField secWeaTxt;
    private javax.swing.JTextField strTxt;
    private javax.swing.JTextField vitTxt;
    // End of variables declaration//GEN-END:variables

   public void cadastraDbf(){
       DeBuffs x = new DeBuffs();
       int buf = comboBdf.getSelectedIndex();
     
       Random dad = new Random();
        DefaultListModel<String> model = new DefaultListModel<String>();
 
        

       switch(buf){
           
           case 0: 
               x.setDamage(dad.nextInt(this.dado()));
               lista.add("Debuff dano de 1"+comboDados.getSelectedItem()); 
                for(String s:lista){
                    model.addElement(s);
                }
               listaDebuffs.setModel(model);
               break;
           case 1:
               x.setLightning(dad.nextInt(this.dado()));
               lista.add("Debuff Lightning");
              for(String s:lista){
                    model.addElement(s);
                }
               listaDebuffs.setModel(model);
               break;
           case 2:
               x.setDowndef(dad.nextInt(this.dado()));
               lista.add("Debuff Defesa");
               for(String s:lista){
                    model.addElement(s);
                }
               listaDebuffs.setModel(model);
               break;
           case 3:
               x.setPower(dad.nextInt(this.dado()));
               lista.add("Buff Dano de 1" +comboDados.getSelectedItem());
               for(String s:lista){
                    model.addElement(s);
                }
               listaDebuffs.setModel(model);
               break;
           case 4:
               x.setShield(dad.nextInt(this.dado()));
               lista.add("Buff Defesa");
               for(String s:lista){
                    model.addElement(s);
                }
               listaDebuffs.setModel(model);
               break;
           default: break;
            
       } 
   }
   public int dado(){
       int d= comboDados.getSelectedIndex();
       
       switch(d){
           case 0:
               return 5;
           case 1:
               return 7;
           case 2:
               return 9;
           case 3:
               return 11;
           case 4:
               return 13;
           default: return 0;
               
       }
       
   }
   
}
